version: '3'

services:
  godebug_example:
    image: aligator/godebug:latest
    ports:
      - 40000:40000
      - 8080:8080
    volumes:
      - .:/build

    # Needed for debugging in Docker.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - CONSUL_HOST=consul-service:8500
    networks:
      - scayle_scayle

networks:
  scayle_scayle:
    external: true